name: conditional-workflow

on:
  push:
    branches:
      - 'feature/**'
jobs:
  build:
    if: startsWith(github.ref_name, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "test"
